### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by DuanYouming** [takahirom/android-postfix-plugin#10]
Plugin Error
update to Version: 2.0.3 .    Android Postfix Completion threw an uncaught NoClassDefFoundError. Disable Plugin
why?

**Comment by takahirom** [comment]
Thank you for reporting.
Please tell me Android Studio version.

**Comment by zgh0711** [comment]
I have the same question.
When I use the .find command, plugin is an error.
The Android Studio version is 2.1.1

**Comment by takahirom** [comment]
Thank you! I will try. And I will fix that as soon as possible.

**Comment by takahirom** [comment]
I installed below.
* Android Studio 2.1.1
* Android Postfix Completion 2.0.3

I can use .find command...
If you can find stack trace, Please copy and paste.

**Comment by takahirom** [comment]
@DuanYouming 
@zgh0711 

I installed below.
- Android Studio 2.1.1
- Android Postfix Completion 2.0.3

I can use .find command...
If you can find stack trace, Please copy and paste.

**Comment by zgh0711** [comment]
I don't know how to find stack trace,and I find these messages,perhaps it is useful for you.

NoClassDefFoundError: com/android/tools/idea/res/LocalResourceRepository

com/android/tools/idea/res/LocalResourceRepository
java.lang.NoClassDefFoundError: com/android/tools/idea/res/LocalResourceRepository
    at com.kogitune.intellij.codeinsight.postfix.templates.surround.FindViewByIdTemplate.addExprVariable(FindViewByIdTemplate.java:61)
    at com.kogitune.intellij.codeinsight.postfix.internal.AbstractRichStringBasedPostfixTemplate.expandForChooseExpression(AbstractRichStringBasedPostfixTemplate.java:73)
    at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.expand(PostfixTemplateWithExpressionSelector.java:69)
    at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate$1$1.run(PostfixLiveTemplate.java:228)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
    at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate$1.run(PostfixLiveTemplate.java:226)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
    at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.expandTemplate(PostfixLiveTemplate.java:223)
    at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.expand(PostfixLiveTemplate.java:134)
    at com.intellij.codeInsight.template.impl.CustomLiveTemplateLookupElement.expandTemplate(CustomLiveTemplateLookupElement.java:67)
    at com.intellij.codeInsight.template.impl.CustomLiveTemplateLookupElement.handleInsert(CustomLiveTemplateLookupElement.java:63)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$10.run(CodeCompletionHandlerBase.java:706)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItem(CodeCompletionHandlerBase.java:696)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.access$500(CodeCompletionHandlerBase.java:70)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$7.perform(CodeCompletionHandlerBase.java:626)
    at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
    at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
    at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
    at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItemHonorBlockSelection(CodeCompletionHandlerBase.java:614)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lookupItemSelected(CodeCompletionHandlerBase.java:583)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$2.itemSelected(CompletionProgressIndicator.java:122)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.fireItemSelected(LookupImpl.java:823)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:525)
    at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:464)
    at com.intellij.codeInsight.lookup.impl.actions.ChooseItemAction$Handler.execute(ChooseItemAction.java:71)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doExecute(EditorActionHandler.java:172)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
    at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.android.tools.idea.res.LocalResourceRepository PluginClassLoader[com.kogitune.intellij.androidPostfixCompletion, 2.0.3]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 49 more

**Comment by zgh0711** [comment]
Can you provide the earlier version at first?

**Comment by takahirom** [comment]
@zgh0711 
You can download here.
https://github.com/takahirom/android-postfix-plugin/releases/download/2.0.1/android-postfix-plugin-2.0.1.jar
And Please apply by `Settings -> Plugins -> Install plugin from disk...`

**Comment by zgh0711** [comment]
OK,thanks!

**Comment by zgh0711** [comment]
![20160718110801](https://cloud.githubusercontent.com/assets/15401997/16905430/5e04942e-4cd8-11e6-845e-b729eead6428.jpg)
@takahirom 
When I install the 2.0.1 .The android studio tell me that "the plugin is incompatible with this installation".

**Comment by takahirom** [comment]
@zgh0711
Probably, You should uninstall plugin, and retry install.
I'm sorry to take the time

**Comment by zgh0711** [comment]
I've been uninstalled and restart the computer many times.
It also can't install.
Perhaps because of I used the Windows PC?

**Comment by takahirom** [comment]
@zgh0711 
Sorry .. I had the wrong file.
Please try this file.
https://plugins.jetbrains.com/plugin/download?pr=&updateId=22631

**Comment by zgh0711** [comment]
OK,The plugin is already works.
Thank you very much.

**Comment by priesdelly** [comment]
I have same problem.

**Comment by takahirom** [comment]
You can use Android Studio 2.2 or 2.3, and probably It not cause NoClassDefFoundError.
If It occurred ,please open new issue.
